public class DFAProcessor {
    /**
     * Filters through a given string and dictates if it is part of the language
     * generated by (a+b)c*
     * @param input Any string to be tested.
     * @return true or false
     */
    public static boolean acceptDFA(String input) {
        //This represents q0, the starting place.
        int state = 0;

        for (int i = 0; i < input.length(); i++) {
            char current = input.charAt(i);

            if (state == 0) {
                if (current == 'a' || current == 'b') {
                    state += 1;
                } else {
                    return false;
                }
            } else if (state == 1) {
                if (current == 'c') {
                    state += 1;
                } else {
                    return false;
                }
            } else if (state > 1) {
                if (current == 'c') {
                    //finalResult = true;
                    state += 1;
                    return true;
                }  else if (current != 'c') {
                    return false;
                }
            }
        }
        return true;
    }
}
